// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.PurchasingPower
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("originalAmount")]
        public long OriginalAmount { get; set; }

        [JsonProperty("originalPeriod")]
        public string OriginalPeriod { get; set; }

        [JsonProperty("adjustedAmount")]
        public double AdjustedAmount { get; set; }

        [JsonProperty("adjustedPeriod")]
        public string AdjustedPeriod { get; set; }

        [JsonProperty("cumulativeInflation")]
        public double CumulativeInflation { get; set; }

        [JsonProperty("multiplier")]
        public double Multiplier { get; set; }

        [JsonProperty("explanation")]
        public string Explanation { get; set; }

        [JsonProperty("fromCPI")]
        public double FromCpi { get; set; }

        [JsonProperty("toCPI")]
        public double ToCpi { get; set; }
    }
}
